[build]
  command = "yarn build-mainnet"
  publish = "build"
  environment = { SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyCiNSdRCp92Z9jZmzJv62ECfWheJPFK4QE" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200